create table if not exists public.recurring_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  type text not null check (type in ('income', 'expense')),
  amount numeric(12, 2) not null check (amount > 0),
  category text not null,
  note text,
  frequency text not null check (frequency in ('weekly', 'monthly')),
  cadence integer not null default 1 check (cadence > 0),
  next_due_date date not null,
  last_logged_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists recurring_transactions_user_id_idx
  on public.recurring_transactions (user_id);

create index if not exists recurring_transactions_due_idx
  on public.recurring_transactions (user_id, next_due_date);

alter table public.recurring_transactions enable row level security;

drop policy if exists "Users can read their recurring transactions" on public.recurring_transactions;
create policy "Users can read their recurring transactions"
on public.recurring_transactions
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their recurring transactions" on public.recurring_transactions;
create policy "Users can insert their recurring transactions"
on public.recurring_transactions
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their recurring transactions" on public.recurring_transactions;
create policy "Users can update their recurring transactions"
on public.recurring_transactions
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their recurring transactions" on public.recurring_transactions;
create policy "Users can delete their recurring transactions"
on public.recurring_transactions
for delete
using (auth.uid() = user_id);
