create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  category text not null,
  monthly_limit numeric(12, 2) not null check (monthly_limit > 0),
  alert_threshold numeric(4, 2) not null default 0.80 check (alert_threshold > 0 and alert_threshold <= 1),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint budgets_user_category_unique unique (user_id, category)
);

create index if not exists budgets_user_id_idx on public.budgets (user_id);

alter table public.budgets enable row level security;

drop policy if exists "Users can read their budgets" on public.budgets;
create policy "Users can read their budgets"
on public.budgets
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their budgets" on public.budgets;
create policy "Users can insert their budgets"
on public.budgets
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their budgets" on public.budgets;
create policy "Users can update their budgets"
on public.budgets
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their budgets" on public.budgets;
create policy "Users can delete their budgets"
on public.budgets
for delete
using (auth.uid() = user_id);

create table if not exists public.savings_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  target_amount numeric(12, 2) not null check (target_amount > 0),
  current_amount numeric(12, 2) not null default 0 check (current_amount >= 0),
  monthly_contribution_target numeric(12, 2) check (
    monthly_contribution_target is null or monthly_contribution_target > 0
  ),
  target_date date,
  status text not null default 'active' check (status in ('active', 'paused', 'completed')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists savings_goals_user_id_idx on public.savings_goals (user_id);
create index if not exists savings_goals_status_idx on public.savings_goals (status);

alter table public.savings_goals enable row level security;

drop policy if exists "Users can read their savings goals" on public.savings_goals;
create policy "Users can read their savings goals"
on public.savings_goals
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their savings goals" on public.savings_goals;
create policy "Users can insert their savings goals"
on public.savings_goals
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their savings goals" on public.savings_goals;
create policy "Users can update their savings goals"
on public.savings_goals
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their savings goals" on public.savings_goals;
create policy "Users can delete their savings goals"
on public.savings_goals
for delete
using (auth.uid() = user_id);
