create table if not exists public.savings_goal_contributions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  goal_id bigint not null references public.savings_goals (id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  contribution_date date not null,
  note text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists savings_goal_contributions_user_id_idx
  on public.savings_goal_contributions (user_id);

create index if not exists savings_goal_contributions_goal_id_idx
  on public.savings_goal_contributions (goal_id);

create index if not exists savings_goal_contributions_date_idx
  on public.savings_goal_contributions (user_id, contribution_date);

alter table public.savings_goal_contributions enable row level security;

drop policy if exists "Users can read their savings goal contributions" on public.savings_goal_contributions;
create policy "Users can read their savings goal contributions"
on public.savings_goal_contributions
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their savings goal contributions" on public.savings_goal_contributions;
create policy "Users can insert their savings goal contributions"
on public.savings_goal_contributions
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their savings goal contributions" on public.savings_goal_contributions;
create policy "Users can update their savings goal contributions"
on public.savings_goal_contributions
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their savings goal contributions" on public.savings_goal_contributions;
create policy "Users can delete their savings goal contributions"
on public.savings_goal_contributions
for delete
using (auth.uid() = user_id);
